"""Promote a local skill/agent/command to a marketplace plugin.

Two modes:

- copy: caller supplies a path to a local marketplace checkout via
  ``checkout=``. The artifact is copied into the right subtree;
  caller commits, pushes, and opens the PR by hand.
- gh:   default. Clones the marketplace into a temporary directory,
  branches, copies, commits, pushes, and runs ``gh pr create``.
"""

import shutil
import subprocess
import tempfile
from datetime import datetime, timezone
from pathlib import Path


class PublishError(RuntimeError):
    pass


ARTIFACT_TYPES = ("skill", "agent", "command")


def detect_kind(path: Path) -> str:
    """Infer artifact type from a path. Raises if ambiguous."""
    if path.is_dir() and (path / "SKILL.md").exists():
        retval = "skill"
        return retval
    parts_lower = [p.lower() for p in path.parts]
    if "skills" in parts_lower:
        retval = "skill"
        return retval
    if "agents" in parts_lower:
        retval = "agent"
        return retval
    if "commands" in parts_lower:
        retval = "command"
        return retval
    raise PublishError(
        f"could not infer artifact type from {path}; pass --type"
    )


def _dest_for(plugin_dir: Path, kind: str, src: Path) -> Path:
    if kind not in ARTIFACT_TYPES:
        raise PublishError(f"unknown artifact type: {kind}")
    retval = plugin_dir / f"{kind}s" / src.name
    return retval


def _copy_into(src: Path, dest: Path) -> None:
    if dest.exists():
        if dest.is_dir():
            shutil.rmtree(dest)
        else:
            dest.unlink()
    dest.parent.mkdir(parents=True, exist_ok=True)
    if src.is_dir():
        shutil.copytree(src, dest)
    else:
        shutil.copy2(src, dest)


def _run(cmd, cwd=None, capture=False):
    res = subprocess.run(
        cmd,
        cwd=cwd,
        check=True,
        text=True,
        capture_output=capture,
    )
    retval = res
    return retval


def publish_local(
    src: Path,
    checkout: Path,
    plugin: str,
    kind: str,
) -> Path:
    """Copy artifact into a local marketplace checkout. Returns dest path."""
    plugin_dir = checkout / "plugins" / plugin
    if not plugin_dir.is_dir():
        raise PublishError(
            f"plugin directory not found: {plugin_dir}"
        )
    dest = _dest_for(plugin_dir, kind, src)
    _copy_into(src, dest)
    retval = dest
    return retval


def publish_gh(
    src: Path,
    marketplace: str,
    plugin: str,
    kind: str,
    title: str = None,
    body: str = None,
    dry_run: bool = False,
) -> str:
    """Full automation: clone, branch, copy, commit, push, gh pr create.

    Returns the PR URL (or, when dry_run is True, the joined command plan).
    """
    if shutil.which("gh") is None:
        raise PublishError("gh CLI not found on PATH")
    if shutil.which("git") is None:
        raise PublishError("git not found on PATH")

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    branch = f"omemepo-publish-{src.name}-{timestamp}"
    repo_url = f"git@github.com:{marketplace}.git"
    pr_title = title or f"Add {kind} {src.name} to {plugin}"
    pr_body = body or (
        f"Promotes `{src.name}` to `plugins/{plugin}/{kind}s/`.\n\n"
        f"Generated by `omemepo publish`."
    )

    if dry_run:
        plan = [
            f"git clone --depth=1 {repo_url} <tmp>",
            f"git -C <tmp> checkout -b {branch}",
            f"copy {src} -> plugins/{plugin}/{kind}s/{src.name}",
            f"git -C <tmp> add plugins/{plugin}/{kind}s/{src.name}",
            f"git -C <tmp> commit -m {pr_title!r}",
            f"git -C <tmp> push -u origin {branch}",
            f"gh pr create --title {pr_title!r} --body <generated>",
        ]
        retval = "\n".join(plan)
        return retval

    workdir = Path(tempfile.mkdtemp(prefix="omemepo-publish-"))
    repo = workdir / "repo"
    _run(["git", "clone", "--depth=1", repo_url, str(repo)])
    _run(["git", "-C", str(repo), "checkout", "-b", branch])

    dest = publish_local(src=src, checkout=repo, plugin=plugin, kind=kind)
    rel = dest.relative_to(repo)
    _run(["git", "-C", str(repo), "add", str(rel)])
    _run(["git", "-C", str(repo), "commit", "-m", pr_title])
    _run(["git", "-C", str(repo), "push", "-u", "origin", branch])

    res = _run(
        ["gh", "pr", "create", "--title", pr_title, "--body", pr_body],
        cwd=str(repo),
        capture=True,
    )
    url = res.stdout.strip()
    retval = url
    return retval
